import { Activity, DefaultCategories } from '@/types/schedule';

export const initialActivities: Activity[] = [
  {
    id: 1,
    time: '07:00',
    duration: 60,
    activity: 'Wake up, morning routine, quick walk with dog',
    category: [DefaultCategories.Personal],
  },
  {
    id: 2,
    time: '08:00',
    duration: 45,
    activity: 'Breakfast & meal prep for the day',
    category: [DefaultCategories.Health],
  },
  {
    id: 3,
    time: '08:45',
    duration: 15,
    activity: "Dog's breakfast",
    category: [DefaultCategories.PetCare],
    important: true,
  },
  {
    id: 4,
    time: '09:00',
    duration: 120,
    activity: 'Technical interview prep / coding practice',
    category: [DefaultCategories.Career],
  },
  {
    id: 5,
    time: '11:00',
    duration: 60,
    activity: 'Gym workout',
    category: [DefaultCategories.Health],
  },
  {
    id: 6,
    time: '12:00',
    duration: 30,
    activity: 'Post-workout shower & quick lunch',
    category: [DefaultCategories.Health],
  },
  {
    id: 7,
    time: '12:30',
    duration: 120,
    activity: 'Game development project work',
    category: [DefaultCategories.Portfolio],
  },
  {
    id: 8,
    time: '11:30',
    duration: 60,
    activity: 'Job applications & networking',
    category: [DefaultCategories.Career],
  },
  {
    id: 9,
    time: '13:30',
    duration: 75,
    activity: 'Content creation / dev diary',
    category: [DefaultCategories.Content],
  },
  {
    id: 10,
    time: '14:45',
    duration: 15,
    activity: "Dog's dinner",
    category: [DefaultCategories.PetCare],
    important: true,
  },
  {
    id: 11,
    time: '15:00',
    duration: 60,
    activity: 'Long walk with dog',
    category: [DefaultCategories.PetCare, DefaultCategories.Health],
  },
  {
    id: 12,
    time: '16:00',
    duration: 120,
    activity: 'Quality time with fiancé (dinner & activities)',
    category: [DefaultCategories.Personal],
  },
  {
    id: 13,
    time: '17:00',
    duration: 60,
    activity: 'Leisure time (gaming/streams)',
    category: [DefaultCategories.Leisure],
  },
  {
    id: 14,
    time: '18:00',
    duration: 30,
    activity: 'Additional project work or content editing',
    category: [DefaultCategories.Flexible],
  },
  {
    id: 15,
    time: '19:30',
    duration: 60,
    activity: 'Evening routine & wind down',
    category: [DefaultCategories.Personal],
  },
];
