import { Activity, Categories } from '@/types/schedule';

export const initialActivities: Activity[] = [
  {
    id: 1,
    time: '07:00',
    duration: 60,
    activity: 'Wake up, morning routine, quick walk with dog',
    category: [Categories.Personal],
  },
  {
    id: 2,
    time: '08:00',
    duration: 45,
    activity: 'Breakfast & meal prep for the day',
    category: [Categories.Health],
  },
  {
    id: 3,
    time: '08:45',
    duration: 15,
    activity: "Dog's breakfast",
    category: [Categories.PetCare],
    important: true,
  },
  {
    id: 4,
    time: '09:00',
    duration: 120,
    activity: 'Technical interview prep / coding practice',
    category: [Categories.Career],
  },
  {
    id: 5,
    time: '11:00',
    duration: 60,
    activity: 'Gym workout',
    category: [Categories.Health],
  },
  {
    id: 6,
    time: '12:00',
    duration: 30,
    activity: 'Post-workout shower & quick lunch',
    category: [Categories.Health],
  },
  {
    id: 7,
    time: '12:30',
    duration: 120,
    activity: 'Game development project work',
    category: [Categories.Portfolio],
  },
  {
    id: 8,
    time: '2:30',
    duration: 60,
    activity: 'Job applications & networking',
    category: [Categories.Career],
  },
  {
    id: 9,
    time: '3:30',
    duration: 75,
    activity: 'Content creation / dev diary',
    category: [Categories.Content],
  },
  {
    id: 10,
    time: '4:45',
    duration: 15,
    activity: "Dog's dinner",
    category: [Categories.PetCare],
    important: true,
  },
  {
    id: 11,
    time: '5:00',
    duration: 60,
    activity: 'Long walk with dog',
    category: [Categories.PetCare, Categories.Health],
  },
  {
    id: 12,
    time: '6:00',
    duration: 120,
    activity: 'Quality time with fiancé (dinner & activities)',
    category: [Categories.Personal],
  },
  {
    id: 13,
    time: '8:00',
    duration: 60,
    activity: 'Leisure time (gaming/streams)',
    category: [Categories.Leisure],
  },
  {
    id: 14,
    time: '9:00',
    duration: 30,
    activity: 'Additional project work or content editing',
    category: [Categories.Flexible],
  },
  {
    id: 15,
    time: '9:30',
    duration: 60,
    activity: 'Evening routine & wind down',
    category: [Categories.Personal],
  },
];
